# Generated by Django 3.1.4 on 2020-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201220_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='BTC Admin', max_length=50, null=True),
        ),
    ]
