# Generated by Django 3.1.4 on 2020-12-24 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201224_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='BTC Admin', max_length=110, null=True),
        ),
        migrations.CreateModel(
            name='MarketingGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(max_length=110)),
                ('legal_name', models.CharField(blank=True, max_length=110, null=True)),
                ('bussines_field', models.CharField(max_length=110)),
                ('land_line', models.CharField(blank=True, max_length=30, null=True)),
                ('trading_address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=25, null=True)),
                ('decision_maker', models.CharField(blank=True, max_length=110, null=True)),
                ('mobile', models.CharField(blank=True, max_length=27, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('W', 'In Waiting Queue'), ('P', 'Pending')], default='W', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('last_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Updated_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
