# Generated by Django 3.1.4 on 2020-12-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201224_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketingGoals',
            new_name='MarketingGoal',
        ),
    ]
