# Generated by Django 3.1.4 on 2020-12-26 15:50

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201224_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_to_face_saled', models.PositiveIntegerField(blank=True, null=True, validators=[core.models.percent_validator])),
                ('atv', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_card_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_total_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interchange', models.FloatField(blank=True, null=True)),
                ('authorizathion_fee', models.FloatField(blank=True, null=True)),
                ('pci_dss', models.FloatField(blank=True, null=True)),
                ('american_express_fee', models.FloatField(blank=True, null=True)),
                ('acquire_name', models.CharField(choices=[('EP', 'Emerchant Pay'), ('FD', 'First Data')], max_length=25)),
                ('m_id', models.CharField(max_length=55)),
                ('amex_m_id', models.CharField(max_length=55)),
                ('t_id', models.CharField(max_length=55)),
                ('pci_due_date', models.DateField(blank=True, null=True)),
                ('live_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(max_length=110)),
                ('legal_name', models.CharField(max_length=110)),
                ('business_type', models.CharField(choices=[('Acc', 'Accommodation'), ('AcAu', 'Accountants and Auditors'), ('BCM', 'Builders, Carpenters and Materials'), ('CF', 'Carpets nd Floornig'), ('Cat', 'Caterers'), ('CNE', 'Cinema, Nightclub and Entertainment'), ('CMS', 'Cleaning and Maintenance Servises'), ('CA', 'Clothing and Accessories'), ('ET', 'Education and Trainig'), ('Est', 'Estate Agents'), ('FDN', 'Food, Drink and Newsagents'), ('Fur', 'Furniture'), ('GCL', 'Garden Centers and Landscaping'), ('GAC', 'Gift Shopes, Arts and Crafts'), ('HB', 'Hair and Beauty'), ('HMS', 'Health and Mediacal Services'), ('HPA', 'Heating, Plumping and Air Conditioning'), ('HAD', 'Home Appliances and Decor'), ('Jew', 'Jewellery'), ('Lth', 'Leather Goods'), ('MSP', 'Motor Sales, Servicing and parts'), ('Pet', 'Pet Services'), ('PMS', 'Petrol and Motorway Service Stations'), ('Pho', 'Photography'), ('RPF', 'Restaurants, Pubs and Fast Food'), ('SRF', 'Sports and Recreation Faculties'), ('Txi', 'Taxis'), ('TTA', 'Theaters and Ticket Agencies'), ('Oth', 'Other')], max_length=50)),
                ('legal_entity', models.CharField(choices=[('ST', 'Sole Trader'), ('Pa', 'Partnership'), ('PrLC', 'Private Limited Company'), ('PuLC', 'Public Limited Company'), ('LLP', 'Limited Liability Partnership'), ('Ch', 'Charity'), ('Oth', 'Other')], max_length=50)),
                ('business_date', models.DateField(blank=True, null=True)),
                ('registered_address', models.CharField(max_length=510)),
                ('registered_postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('business_postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('company_number', models.CharField(blank=True, max_length=50, null=True)),
                ('land_line', models.CharField(blank=True, max_length=25, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('director_name', models.CharField(blank=True, max_length=110, null=True)),
                ('director_phone', models.CharField(blank=True, max_length=55, null=True)),
                ('director_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('director_address', models.CharField(blank=True, max_length=255, null=True)),
                ('director_postal_code', models.CharField(blank=True, max_length=55, null=True)),
                ('director_birth_date', models.DateField(blank=True, null=True)),
                ('sort_code', models.CharField(max_length=55)),
                ('issuing_bank', models.CharField(max_length=110)),
                ('account_number', models.CharField(max_length=110)),
                ('business_bank_name', models.CharField(max_length=110)),
                ('partner_name', models.CharField(blank=True, max_length=110, null=True)),
                ('partner_address', models.CharField(blank=True, max_length=255, null=True)),
                ('shareholder', models.PositiveIntegerField(blank=True, null=True, validators=[core.models.percent_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PlaceCountry', to='core.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Creator', to=settings.AUTH_USER_MODEL)),
                ('director_natinality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DirectorNationality', to='core.country')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Updator', to=settings.AUTH_USER_MODEL)),
                ('partner_nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PartnerNationality', to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='TradingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=510)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('direct_debit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direct_debit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ordered_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.costumer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.virtualservice')),
            ],
        ),
        migrations.CreateModel(
            name='ContractPOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pos')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.costumer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
