# Generated by Django 3.1.4 on 2021-01-10 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210106_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.costumer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractpos',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_pos', to='core.contract'),
        ),
        migrations.AlterField(
            model_name='contractpos',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_pos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractpos',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_contract', to='core.pos'),
        ),
        migrations.AlterField(
            model_name='contractservice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_service', to='core.contract'),
        ),
        migrations.AlterField(
            model_name='contractservice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_service_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_contracr', to='core.virtualservice'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costumer_location', to='core.country'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costumers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='director_natinality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='core.country'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costumers_last_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='partner_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_location', to='core.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketinggoal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketinggoal',
            name='last_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='midrevenue',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mid_revenues', to='core.contract'),
        ),
        migrations.AlterField(
            model_name='midrevenue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mid_revenues_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paperroll',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_rolls', to='core.costumer'),
        ),
        migrations.AlterField(
            model_name='paperroll',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_rolls_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.contract'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pos',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pos',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='core.posmodel'),
        ),
        migrations.AlterField(
            model_name='poscompany',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_models', to='core.poscompany'),
        ),
        migrations.AlterField(
            model_name='posmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_models_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradingaddress',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_address', to='core.costumer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_nationalities', to='core.country'),
        ),
        migrations.AlterField(
            model_name='virtualservice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
    ]
