# Generated by Django 3.1.4 on 2021-01-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210110_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumer',
            old_name='director_natinality',
            new_name='director_nationality',
        ),
    ]
