# Generated by Django 3.1.4 on 2021-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210117_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
