# Generated by Django 3.1.4 on 2021-01-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pos_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_contract', to='core.virtualservice'),
        ),
    ]
