# Generated by Django 3.1.4 on 2021-02-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210117_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketinggoal',
            old_name='bussines_field',
            new_name='business_field',
        ),
    ]
