# Generated by Django 3.1.6 on 2021-02-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210204_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractpos',
            old_name='cost',
            new_name='hardware_cost',
        ),
        migrations.AddField(
            model_name='contractpos',
            name='software_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
